### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wqy0916** [bitsavers/eu_ex#1]
[2022-03-10 23:40:57] ******************************
[2022-03-10 23:40:57] [EUserv] Renewing the 1st account...
[2022-03-10 23:40:57] [PIN Solver] Getting login PIN from Mailparser...
[2022-03-10 23:40:57] [PIN Solver] PIN: GJ3S9T
[2022-03-10 23:40:57] [PIN Solver] Login PIN Verification passed
[2022-03-10 23:40:57] [EUserv] The 1st account is detected with 1 VPS, renewals are being attempted...
[2022-03-10 23:40:57] Traceback (most recent call last):
[2022-03-10 23:40:57]   File "/root/workspace/[main.py](http://main.py/)", line 1093, in <module>
[2022-03-10 23:40:57]     lambda_handler(None, None)
[2022-03-10 23:40:57]   File "/root/workspace/[main.py](http://main.py/)", line 1083, in lambda_handler
[2022-03-10 23:[40]():57]     EUserv(customer_ids=CUSTOMERIDS, passwords=PASSWORDS).compute()
[2022-03-10 23:40:57]   File "/root/workspace/main.py", line 10[41](), in compute
[2022-03-10 23:40:57]     if not renew(
[2022-03-10 23:40:57] NameError: name 'renew' is not defined
script returned exit code 1

**Comment by ZetaoYang** [comment]
暂时手动改为`if not self.renew`

**Comment by wqy0916** [comment]
[2022-03-11 00:15:24] ******************************
[2022-03-11 00:15:24] [EUserv] Renewing the 1st account...
[2022-03-11 00:15:24] [PIN Solver] Getting login PIN from Mailparser...
[2022-03-11 00:15:24] [PIN Solver] PIN: MVGU87
[2022-03-11 00:15:24] [PIN Solver] Login PIN Verification passed
[2022-03-11 00:15:24] [EUserv] The 1st account is detected with 1 VPS, renewals are being attempted...
[2022-03-11 00:15:24] [Mailparser] PIN: 940685
[2022-03-11 00:15:24] Traceback (most recent call last):
[2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1093, in <module>
[2022-03-11 00:15:24]     lambda_handler(None, None)
[2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1083, in lambda_handler
[2022-03-11 00:15:24]     EUserv(customer_ids=CUSTOMERIDS, passwords=PASSWORDS).compute()
[2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1041, in compute
[2022-03-11 00:15:24]     if not self.renew(
[2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 847, in renew
[2022-03-11 00:15:24]     if not json.loads(f.text)["rs"] == "success":
[2022-03-11 00:15:24] NameError: name 'f' is not defined
script returned 
![QQ截图20220311001616](https://user-images.githubusercontent.com/38550132/157706919-6bcc5cfd-b65d-4860-95e6-fcc1b4c1b156.png)
exit code 1
请问是修改这里对吧

**Comment by ZetaoYang** [comment]
> [2022-03-11 00:15:24] ******************************
> [2022-03-11 00:15:24] [EUserv] Renewing the 1st account...
> [2022-03-11 00:15:24] [PIN Solver] Getting login PIN from Mailparser...
> [2022-03-11 00:15:24] [PIN Solver] PIN: MVGU87
> [2022-03-11 00:15:24] [PIN Solver] Login PIN Verification passed
> [2022-03-11 00:15:24] [EUserv] The 1st account is detected with 1 VPS, renewals are being attempted...
> [2022-03-11 00:15:24] [Mailparser] PIN: 940685
> [2022-03-11 00:15:24] Traceback (most recent call last):
> [2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1093, in <module>
> [2022-03-11 00:15:24]     lambda_handler(None, None)
> [2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1083, in lambda_handler
> [2022-03-11 00:15:24]     EUserv(customer_ids=CUSTOMERIDS, passwords=PASSWORDS).compute()
> [2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 1041, in compute
> [2022-03-11 00:15:24]     if not self.renew(
> [2022-03-11 00:15:24]   File "/root/workspace/[main.py](http://main.py/)", line 847, in renew
> [2022-03-11 00:15:24]     if not json.loads(f.text)["rs"] == "success":
> [2022-03-11 00:15:24] NameError: name 'f' is not defined
> script returned 
> ![QQ截图20220311001616](https://user-images.githubusercontent.com/38550132/157706919-6bcc5cfd-b65d-4860-95e6-fcc1b4c1b156.png)
> exit code 1
> 请问是修改这里对吧

是的

**Comment by ZetaoYang** [comment]
fixed https://github.com/bitsavers/eu_ex/commit/ec5531159810a3574637d8c2dd7a14c6c2286159

**Comment by wqy0916** [comment]
> 固定 [ec55311](https://github.com/bitsavers/eu_ex/commit/ec5531159810a3574637d8c2dd7a14c6c2286159)

但是我修改了 还是报错 图片上面就是错误代码

**Comment by ZetaoYang** [comment]
fixed https://github.com/bitsavers/eu_ex/commit/6464d6dbf1e5c164258ccced08c833293f3cc717

**Comment by wqy0916** [comment]
> 固定 [6464d6d](https://github.com/bitsavers/eu_ex/commit/6464d6dbf1e5c164258ccced08c833293f3cc717)

谢谢 可以使用了
